### ISSUE TITLE
Error in Console on missing ai-block.svg

### ISSUE THREAD

**Issue by nofonbg** [mebis-lp/moodle-block_ai_chat#13]
When the modal for the AI chat block is not displayed or is hidden like the block, the console displays an error message because of missing icon, since the path in the code is passed incorrectly. When the block is hidden, the wwwroot part is missing in path.
Example:
 img src="/blocks/ai_chat/pix/ai-icon.svg" alt="" class="ai_chat_icon" 
 textarea ...

**Comment by PhMemmel** [comment]
Hi @nofonbg and thanks for the report. Unfortunately, I cannot reproduce this. I have an idea what could be wrong, but to be sure I need to reproduce it first. Should I see the error whenever an "AI Chat" block is present in a course? Could you please provide a screenshot/a short screencast? Do you have some special setup like moodle in a subdirectory of your webserver?

**Comment by nofonbg** [comment]
The block is configured so that it is displayed everywhere (*), 
moodle is located in the subfolder /localhost/moodle5. 
In the highlighted line, no wwwroot is added at all
![Bildschirmfoto 2024-12-27 um 16 21 49](https://github.com/user-attachments/assets/88bb40c8-7584-4edc-ac9e-257dcce2e473)

**Comment by PhMemmel** [comment]
Thank you for your feedback. Would you mind testing the code in #14?

**Comment by nofonbg** [comment]
Tested with complete cache reset, now I have "http://localhost/" but not my wwwroot  "http://localhost/moodle5".

GET | http://localhost/blocks/ai_chat/pix/ai-icon.svg 
should be 
GET | http://localhost/moodle5/blocks/ai_chat/pix/ai-icon.svg

**Comment by PhMemmel** [comment]
Fix confirmed by @nofonbg. Thanks!
